name: Tools Update Workflow

on:
  push:
    branches:
      - main

jobs:
  check-tools:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        run: git clone https://github.com/dragmine149/dragmine149.github.io.git .

      - name: Check if tools binary updated
        id: check-tools
        run: |
          LAST_SRC_COMMIT=$(git log -1 --format=%ct tools/src/)
          LAST_BIN_COMMIT=$(git log -1 --format=%ct tools/tools)

          echo "$LAST_SRC_COMMIT"
          echo "$LAST_BIN_COMMIT"

          if [ $LAST_SRC_COMMIT -gt $LAST_BIN_COMMIT ]; then
            echo "::error::Tools source updated but binary not rebuilt"
            exit 1
          fi
